---
Name: goldfinch-component-faq
---
Goldfinch\Component\FAQ\Admin\FAQAdmin:
  extensions:
    - Goldfinch\Helpers\Extensions\BlocksAdminExtension

Goldfinch\Component\FAQ\Blocks\FAQBlock:
  extensions:
    - Goldfinch\Helpers\Extensions\BaseElementExtension

Goldfinch\Component\FAQ\Models\FAQItem:
  extensions:
    - Goldfinch\Helpers\Extensions\DataObjectSluggable

Goldfinch\Component\FAQ\Models\FAQCategory:
  extensions:
    - Goldfinch\Helpers\Extensions\DataObjectSluggable

---
Name: goldfinch-component-faq-icon
Only:
  moduleexists: "goldfinch/enchantment"
---
Goldfinch\Component\FAQ\Admin\FAQAdmin:
  menu_icon_class: "bi-patch-question-fill"

Goldfinch\Component\FAQ\Blocks\FAQBlock:
  icon: "bi-patch-question-fill"
